import { cn } from "@/lib/utils";
import { severityColor, statusColor } from "@/lib/utils";
import { Badge } from "./badge";

export function SeverityBadge({ severity }: { severity: string }) {
  return <Badge className={cn(severityColor[severity] || "")}>{severity}</Badge>;
}

export function StatusBadge({ status }: { status: string }) {
  return <Badge className={cn(statusColor[status] || "")}>{status}</Badge>;
}

export function Spinner({ className }: { className?: string }) {
  return (
    <div
      className={cn("h-4 w-4 animate-spin rounded-full border-2 border-border border-t-primary", className)}
      role="status"
      aria-label="loading"
    />
  );
}

export function EmptyState({ title, description }: { title: string; description?: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      <p className="text-sm font-medium text-foreground">{title}</p>
      {description && <p className="text-xs text-muted mt-1 max-w-sm">{description}</p>}
    </div>
  );
}

export function LoadingBlock() {
  return (
    <div className="flex items-center justify-center py-16">
      <Spinner className="h-6 w-6" />
    </div>
  );
}

export function ErrorBlock({ message }: { message: string }) {
  return (
    <div className="rounded-md border border-danger/40 bg-danger/10 px-4 py-3 text-sm text-danger">{message}</div>
  );
}

export function AiUnavailableNotice({ message }: { message?: string }) {
  return (
    <div className="rounded-md border border-warning/40 bg-warning/10 px-4 py-3 text-sm text-warning">
      AI not connected{message ? ` — ${message}` : ""}. Install Ollama and pull the configured model to enable this
      feature.
    </div>
  );
}

/** Renders the right notice for an AI-backed action's error: the
 * "install Ollama" notice only for a genuine AI_UNAVAILABLE error, a plain
 * error message for everything else (expired session, validation, network) --
 * those aren't an AI problem and telling the user to install Ollama for them
 * is actively misleading. Pass `isAiUnavailable` from `isAiUnavailableError()`
 * (src/lib/api.ts) computed in the mutation's onError. */
export function AiActionError({ message, isAiUnavailable }: { message: string; isAiUnavailable: boolean }) {
  return isAiUnavailable ? <AiUnavailableNotice message={message} /> : <ErrorBlock message={message} />;
}

const AI_SUMMARY_HEADINGS = [
  "Problem",
  "Why it matters",
  "Why this order",
  "Recommended priorities",
  "Suggested next step",
];

/** Splits the model's free-text response into labeled sections, keyed on the
 * headings we asked it to use (see app/ai/prompts.py). Falls back to a single
 * unlabeled block if the model didn't follow the format exactly -- we never
 * hide or reformat what it actually said. */
function parseAiSections(text: string): { heading: string | null; body: string }[] {
  const headingPattern = new RegExp(`^\\s*(${AI_SUMMARY_HEADINGS.join("|")})\\s*:?\\s*$`, "i");
  const lines = text.split("\n");
  const sections: { heading: string | null; body: string[] }[] = [];
  let current: { heading: string | null; body: string[] } = { heading: null, body: [] };

  for (const line of lines) {
    const match = line.match(headingPattern);
    if (match) {
      if (current.heading || current.body.some((l) => l.trim())) sections.push(current);
      current = { heading: match[1], body: [] };
    } else {
      current.body.push(line);
    }
  }
  if (current.heading || current.body.some((l) => l.trim())) sections.push(current);

  return sections.map((s) => ({ heading: s.heading, body: s.body.join("\n").trim() })).filter((s) => s.body);
}

export function AiSummaryPanel({ text, model }: { text: string; model?: string }) {
  const sections = parseAiSections(text);
  return (
    <div className="space-y-3">
      {sections.map((s, i) => (
        <div key={i}>
          {s.heading && <p className="text-xs font-semibold text-primary mb-1">{s.heading}</p>}
          <p className="text-sm whitespace-pre-line leading-relaxed">{s.body}</p>
        </div>
      ))}
      {model && <p className="text-[11px] text-muted pt-1">Generated by local model: {model}</p>}
    </div>
  );
}
