#!/usr/bin/env bash
# Starts the Fabric gateway sidecar (Node) against the local network,
# using the Org1 Admin identity generated by cryptogen.
set -euo pipefail
export MSYS_NO_PATHCONV=1
export MSYS2_ARG_CONV_EXCL="*"
cd "$(dirname "$0")/../gateway-service"

NETWORK_DIR="$(cd ../network && pwd -W 2>/dev/null || cygpath -w "$(pwd)/../network")"
ORG1_DIR="$NETWORK_DIR/crypto-config/peerOrganizations/org1.securityaudit.com"

export PEER_ENDPOINT="localhost:7051"
export PEER_HOST_ALIAS="peer0.org1.securityaudit.com"
export MSP_ID="Org1MSP"
export CERT_PATH="$ORG1_DIR/users/Admin@org1.securityaudit.com/msp/signcerts/Admin@org1.securityaudit.com-cert.pem"
export KEY_DIRECTORY_PATH="$ORG1_DIR/users/Admin@org1.securityaudit.com/msp/keystore"
export TLS_CERT_PATH="$ORG1_DIR/peers/peer0.org1.securityaudit.com/tls/ca.crt"
export CHANNEL_NAME="securityaudit"
export CHAINCODE_NAME="security-audit-chaincode"
export PORT="4001"

if [ ! -f "dist/index.js" ]; then
  npm run build
fi

echo "Starting Fabric gateway sidecar on port $PORT ..."
nohup node dist/index.js > /tmp/fabric-gateway-service.log 2>&1 &
echo $! > /tmp/fabric-gateway-service.pid
sleep 2
curl -sf http://localhost:$PORT/health || echo "Gateway sidecar not yet healthy -- check /tmp/fabric-gateway-service.log"
